apiVersion: v1
kind: service
metadata:
  name: redis
  labels:
    name: mongo-service
    app : demo-web-app

  spec:
    ports:
      - port : 27017
        targetPort: 27017
    selector:
      name : mongodb-pod
      app: demo-web-app
