apiVersion: v1
kind: service
metadata:
  name: web-service
  labels:
    name: web-service
    app : demo-web-app

  spec:
    type: NodePort
    ports:
      - port : 80
        targetPort: 80
        nodeport: 5000
    selector:
      name : web-app
      app: demo-web-app
~                       
