apiVersion: v1
kind: Pod
metadata:
   name : web-app
   labels:
      name : web-app
      app: demo-web-app
   spec:
      containers:
        - name : demo-web-app
          image: kube/web-app/web-app.yaml  
          ports:
            - containerPort: 80
